# Site settings
title: "Filipe Relvas"
description: "Filipe Relvas' Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Filipe Relvas"
resume_title:                   "Software Engineer"
resume_contact_email:           "filipe.relvas@outlook.pt"
resume_contact_address:         "Avenida Professor Cavaco Silva, Room 2-N9.1 2744-016 Porto Salvo Portugal"
resume_header_contact_info: "Visualization and Intelligent MultiModal Interfaces Group - INESC-ID | Avenida Professor Cavaco Silva, Room 2-N9.1 2744-016 Porto Salvo Portugal | filiperelvas@tecnico.ulisboa.pt"
resume_header_intro: "<p>I love technology in general but my biggest passion is videogames! Ever since I met a red hatted plumber they became a part of my life. Always open to new ideas and interesting discussions, I take work very seriously with a keen eye for detail.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_publications:    true
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/therelvas"
  resume_twitter_url:           "http://twitter.com/therelvas"
  # resume_dribbble_url:          "insert dribbble URL here"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/filiperelvas"
  resume_instagram_url:         "https://www.instagram.com/therelvas"
  # resume_website_url:           "insert personal website URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
